t1 = str(input('escreva uma atividade: '))
t2 = str(input('escreva uma atividade: '))
t2 = str(input('escreva uma atividade: '))
t3 = str(input('escreva uma atividade: '))
t4 = str(input('escreva uma atividade: '))
t5 = str(input('escreva uma atividade: '))
t6 = str(input('escreva uma atividade: '))
t7 = str(input('escreva uma atividade: '))
t8 = str(input('escreva uma atividade: '))
t9 = str(input('escreva uma atividade: '))
t10 = str(input('escreva uma atividade: '))

print(f'Suas tarefas: ')
print(f'tarefa 1: {t1}')
print(f'tarefa 2: {t2}')
print(f'tarefa 3: {t3}')
print(f'tarefa 4: {t4}')
print(f'tarefa 5: {t5}')
print(f'tarefa 6: {t6}')
print(f'tarefa 7: {t7}')
print(f'tarefa 8: {t8}')
print(f'tarefa 9: {t9}')
print(f'tarefa 10: {t10}')